# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-19 19:22
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190118_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity_99',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
