# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190120_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='popularity_99',
            new_name='popularity',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
